version: '2'

services:
  crud-vuejs-firebase:
    container_name: crud-vuejs-firebase
    build: ./
    ports:
      - 8080:8080
    volumes:
      - ./:/var/www
    command: npm run dev || tail -f /dev/null
